coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 1%
    patch:
      default:
        target: 80%
  
  ignore:
    - "backend/tests/"
    - "backend/alembic/"
    - "frontend/src/test-utils.tsx"
    - "frontend/src/setupTests.ts"
    - "**/__tests__/**"
